language: python
services:
  - docker
env:
  global:
    - KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/v2/graphql
    # USER_ID
    - secure: "QgtY/GjtbSoyyx/nwH3r5iDZdxXUsikSP/YSFVjbzWTIsTVswg5cB88+O8JJpadmAKn7x4IFnTeqCtzROFC6Pjb2eb0hWM84bjgItb0yiLNxyVWOknVUvF7pOddUFTcq4sVpe5j4CgnzwvPcQOfDM97nC17r/Pm0R304o6QuiRcIGW/gaUrHYbwbNpVVdrhWhT8jRRE1MxwJkS2nEkeLQUgnbo984W4E646c11/GRY3zl52A9CpsjgYhsprDl5P8bDj1TdqpvVUbSxZj5DItWMZrMC5hbLhE0s7fPBUQXQHasAl/tRnVLmTwV3OyL/wKW3pQVSpi7V62/EcvztsqgZV+V1DR0fnp+OoJ6ZyxTehrGf/NZ6BQJtQSNiXkpB43hgpAZEN3U5CgDD6YU6yemSiaA9eNFwPpA0pGZ+G8w2XOOuV2gWLuCi7A6IFxLq/b/uNQW3Z2pBB/FzdsOb7fuOima4LvVg0PI3/cSpYDq0UKU4LxD5RyuyVKHzW5vmEDvCFqFulKEG/JwCJdUxM+iYglQhlDW+B/R/zp7QLTiY5uHF6kIIooeSBcZtirUmLKQy1RQ6zenszKyPVetuLCs00NW1XbrpEN564TUer62ViXlDH/w7Nt/m7O2NnRbZeoMQXUDRqoEtaKl4M1ZQiNeDYJtFaDcSSQDHD+v8LCQNc="
    # API_KEY
    - secure: "jUI/Yo/laN14nRKyYHodKRc04n6g0L3Fr6i/RlIjZDTaG12lCdb2Vz6pimiKGCFOcaMEm8dypO7McaVjwYdROeVVsdz4RzKw7t8/E9wirG/oUdAmNXmP5q9THx5wNWuBqlpB+NIKIuDivbdYNPJQJwXe+whQ5v3NDQBPH2HSuSvhwUwm3MuHT9Fgg89JvKkcd9L9/GTOlZvQ5n26L/YYtmPFkv6DLxv4WBZiVnEWjBrKQZFQZh01618iQE/pkdkMYIwGtkaybhxAjIz/P2ZPh9bKgXlN5gg7kW2VIo7FOj7tHgxsUnQoA9LLSDhz6GjbqkVudiwJa2C1QByVilGUFHN8OGk2i2/yftSoTGJ4b7vbLxH+X3Gn9dn1gQ98/Dmenh/mjnTv3i9S5BTBjxhQHXaWvaFt2E/jRtQrrqgoL6g3s8fL37rlurMYlUDajuHTnmbDsz/Yd4vNfTfwc6BTx1pNeRzdZA7Pt9wuhNWxR8IiIdakUiJrXgt8kNLb9qLmL7OyRxKEpb57zA4x6qxNEXHNhK6kfaMcSIH910MjOMHZiZ+ByN45FzOZF9BzFtuXhFdPuZQ9EugEQ99YbZRo1yTRRrXJPcAVWkiSh5+cNHTZLzaaBc+V6fH64FAYCtmuLhK2HffNv4cN8gO/d6agWk1f7gFEFWHSl27rDiF7I7s="
    # USER_EMAIL
    - secure: "WxMbEciQ9yhLqhjr636ZceqUj6Xs3DuDBVGpEW2B0zVMVBw2YSeRH6i4OwgPe67xlv6adsQDekO0OdCrNcgx7h9aDU1LDl02p4XytLlRy3aqFdMkhmIAcciH9m8fJSco7lAhHev3JWmGYH/wtn3w5rR2z71t6JJ4975j1xLl29DUYIZf+k0rj6GjoEvdoo515bthX3EmOO1Ybs7YT1gb4netcnvvLqqq6mEwiwknZ13JhXKGBR43etiFprOAdDaK9kiCJ75gVI3YSjPBL1K15ZxZuC9P6G2whpek+QkBqwK32yyOZbSR6qbkRLKCOcJ/cKOw9yl25Ojs+8QHEHLVG4XO3RsZ02kBgDhOzcP+sJAcL0xRH7jXCbo01asr1l5tXTSIsxoih6cwvk51ImmsNfWaO/e9Sv51udwOhga1qQ7el8NGTfTggnUl9I1pIHf9quypc/A2FF/3nUp6UjF5CEJpuy61q+sMhXsKo4XNX6PO0wOe/cZK2MMMEqeTuUBK2vGm5Z1goqzCQ7ODrxaNMzoohBTlA2T6fiknPEYqimuRx/Fins3XZV1mpbAbLyAdxc3qDwc9ilHkk8n/Bi7uPwht2P81ShJUvQYdT3CM94yAWBI6JdLmxHXsG/FDRjhoqbp/oBu+ANf88u3d53kVvG6ytmvGCeNMkknfbYWJLYo="
jobs:
  include:
    # To debug a recipe by running it in a Docker locally as it is run in Travis, launch the following lines:
    #
    # DOCKER_IMAGE=continuumio/anaconda3:2020.02
    # KILI_USER_API_KEY=...
    # KILI_USER_ID=...
    # TRAVIS_BRANCH=...
    #
    # docker pull ${DOCKER_IMAGE}
    #
    # docker run \
    #   --env KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/v1/graphql \
    #   --env KILI_USER_API_KEY=${KILI_USER_API_KEY} \
    #   --env KILI_USER_ID=${KILI_USER_ID} \
    #   --env KILI_USER_EMAIL=${KILI_USER_EMAIL} \
    #   --rm \
    #   -p 10000:8888 \
    #   ${DOCKER_IMAGE} /bin/sh -c "cd /root && \
    #     apt-get update && apt-get install -y gcc && \
    #     git clone --branch ${TRAVIS_BRANCH} https://github.com/kili-technology/kili-playground.git && \
    #     pip install ./kili-playground && \
    #     jupyter notebook --allow-root --ip=0.0.0.0 --port=8888"
    #
    # Then start http://localhost:10000/?token=TOKEN_OUTPUTED_IN_CONSOLE
    - &test-recipes
      stage: Test *.ipynb in recipes
      script:
        - docker pull ${DOCKER_IMAGE}
        - |
          docker run \
            --env KILI_API_ENDPOINT=${KILI_API_ENDPOINT} \
            --env KILI_USER_ID=${KILI_USER_ID} \
            --env KILI_USER_API_KEY=${KILI_USER_API_KEY} \
            --env KILI_USER_EMAIL=${KILI_USER_EMAIL} \
            ${DOCKER_IMAGE} /bin/sh -c "cd /root && \
              apt-get update && apt-get install -y gcc && \
              git clone --branch ${TRAVIS_BRANCH} https://github.com/kili-technology/kili-playground.git && \
              pip install ./kili-playground && \
              jupyter nbconvert \
                --to notebook \
                --ExecutePreprocessor.kernel_name=python3 \
                --ExecutePreprocessor.timeout=1000 \
                --execute /root/kili-playground/${NOTEBOOK_PATH}"
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/transfer_learning_with_yolo.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/import_predictions.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/create_project.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/medical_imaging.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/query_methods.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/import_assets.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/pixel_level_masks.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/import_text_assets.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/export_labels.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/getting-started/getting_started-classification.ipynb
