name: CI
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Pylint test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint kili
  recipes:
    runs-on: ubuntu-latest
    name: Recipes test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download docker image
        run: docker pull continuumio/anaconda3:latest
      - name: Run in docker image
        run: >-
          docker run continuumio/anaconda3:latest /bin/sh -c \
            "cd /root && \
              apt-get update && apt-get install -y gcc && \
              git clone --branch ${GITHUB_REF##*/} https://github.com/kili-technology/kili-playground.git && \
              pip install ./kili-playground && \
              jupyter nbconvert \
                --to notebook \
                --ExecutePreprocessor.kernel_name=python3 \
                --ExecutePreprocessor.timeout=1000 \
                --execute /root/kili-playground/${NOTEBOOK_PATH}"
        env:
          NOTEBOOK_PATH: recipes/import_predictions.ipynb
