name: CI
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Pylint test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint kili
  recipes:
    runs-on: ubuntu-latest
    name: Recipes test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download docker image
        run: docker pull continuumio/anaconda3:2020.02
      - name: Run in docker image
        run: >-
          docker run continuumio/anaconda3:2020.02 /bin/sh -c \
            "cd /root && \
              apt-get update && apt-get install -y gcc && \
              git clone --branch ${GITHUB_REF} https://github.com/kili-technology/kili-playground.git"
