name: CI
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Pylint test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint kili
  recipes:
    runs-on: ubuntu-latest
    name: Recipes test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert nbformat
      - name: Run notebooks
        run: |
          jupyter nbconvert \
                --to notebook \
                --ExecutePreprocessor.kernel_name=python3 \
                --ExecutePreprocessor.timeout=1000 \
                --execute recipes/import_predictions.ipynb
        env:
          KILI_USER_EMAIL: ${{ secrets.KILI_USER_EMAIL }}
